Switch to ntopng3
NethServer/nethserver-ntopng pull request #4
Opened 2017-08-22 14:12 UTC by gsanchietti

2017-08-23 07:47 UTC, filippocarletti approved these changes

2017-08-24 12:56 UTC, DavidePrincipi requested changes

2017-08-24 12:56 UTC, DavidePrincipi commented on createlinks
> +    nethserver-httpd-admin-asyncreload 30
Use event_services() -> httpd-admin reload

2017-08-25 08:02 UTC, DavidePrincipi approved these changes

2017-08-25 08:03 UTC, merged